### ISSUE TITLE
FE - Trang đăng ký, đăng nhập

### ISSUE THREAD

**Issue by TruongNguyen1203** [lamhan3012cmvn/CNPM#26]

**Comment by lamhan3012cmvn** [comment]
Page Login: https://github.com/lamhan3012cmvn/FE_CNPM/blob/master/src/pages/LoginPage/index.js

**Comment by lamhan3012cmvn** [comment]
Page Register: https://github.com/lamhan3012cmvn/FE_CNPM/blob/master/src/pages/RegisterPage/index.js
