### ISSUE TITLE
Yêu cầu phi chức năng

### ISSUE THREAD

**Issue by lamhan3012cmvn** [lamhan3012cmvn/CNPM#6]

**Comment by hieuvo3010** [comment]
Yêu cầu phi chức năng bao gồm:

Yêu cầu về ứng dụng: giao diện dễ nhìn, thanh menu đơn giản, font chữ đẹp, gây thiện cảm với người dùng, ...
Yêu cầu về hiệu quả sử dụng: Ứng dụng phải đáp ứng tốt nhu cầu sử dụng của khách hàng, bảo đảm an toàn dữ liệu khách quan
Yêu cầu về chức năng:
Chức năng tìm kiếm đưa ra các sản phẩm nội thất liên quan đến chủ đề cần tìm.
Đề xuất những nội thất phù hợp với diện tích căn hộ or phòng
Thanh toán online
Yêu cầu về hiệu năng: Ứng dụng chạy mượt mà, không phát sinh lỗi trong quá trình sử dụng.
Yêu cầu về không gian: Ứng dụng có size không quá lớn khoảng dưới 50MB
