### ISSUE TITLE
User Hệ Thống

### ISSUE THREAD

**Issue by lamhan3012cmvn** [lamhan3012cmvn/CNPM#7]

**Comment by holmeszptd** [comment]
Admin: quản trị viên hệ thống, có chức năng quản lý tài khoản khách hàng, tổng doanh thu, 
đưa những mấu thiết kế phù hợp với căn hộ để đưa ra kết quả tót cho khách hàng
Customer: khách hàng, là người sử dụng các chức năng của ứng dụng.
